[Week1] Step1 미션 제출
MalibinStudy/LottoApp pull request #12
Opened 2023-01-30 09:41 UTC by murjune

- 커밋을 테스트하는 함수별로 쪼개는게 좋을까요??  
- 조금 길더라도 테스트 함수 네이밍을 자세하게 하는게 좋으려나요..  
- Result.getOrNull()로 예외처리를 하였는데 exceptionOrNull() 함수를 사용해서 어떤 예외인지까지 처리하는게 좋으려나요
- `assertThrows`라는 함수가 있던데 runCatching으로 예외처리를 하는 이유가 있을까요?!  

처음 테스트 코드를 작성하는거라 부족한 부분이 많을 것 같네요.. 리뷰 잘 부탁드립니다  😁

2023-01-30 13:13 UTC, malibinYun requested changes
1단계 미션 고생 많으셨어요!! 💪
테스트가 처음이심에도 열심히 잘 작성해주셨네요! 👍👍
테스트코드 작성이 많이 익숙해지셨으면 좋겠네요 😊

리뷰 남겨두었으니 확인 부탁드려요 :)
질문 주신 부분들은 코멘트 달아두었어요.
리뷰 반영이 끝나면 슬랙에 저를 멘션해서 리뷰 반영했다고 메시지 남겨주세요!
혹은, 이 PR에 코멘트를 달아주셔도 됩니다. 🙂

2023-01-30 13:13 UTC, malibinYun commented on README.md
> +- [x] has() 는 LottoTicket에 특정 LottoNumber가 포함되어 있는지 확인한다.
요구사항을 잘 정리해주셨네요 👍👍

2023-01-30 13:13 UTC, malibinYun commented on domain/src/test/java/com/malibin/study/domain/lotto/LottoNumberTest.kt
> +    }
다른 범위 외의 숫자로도 가져올 수 없음을 테스트해보는 것은 어떨까요?
1~45이니, 양 옆 범위 끝 수를 사용해보는 것도 좋은 방법이라 생각해요 :)

2023-01-30 13:13 UTC, malibinYun commented on domain/src/test/java/com/malibin/study/domain/lotto/result/MoneyTest.kt
> +
객체를 만들 수 없는 경우를 잘 테스트해주셨네요!!

> assertThrows라는 함수가 있던데 runCatching으로 예외처리를 하는 이유가 있을까요?!

네, assertThrows라는 함수를 활용해볼 수 있어요.
다만, 사용하게 되면, when 과 then이 하나로 합쳐지는 상황이 발생해요.
그렇기에 저는 분리하는 것이 가독성 향상에 더 도움이 된다고 생각했어요 :)

더 나은 방법이 생각나신다면 반영해보셔도 좋겠어요! 😊

2023-01-30 13:13 UTC, malibinYun commented on domain/src/test/java/com/malibin/study/domain/lotto/result/MoneyTest.kt
> +    }
여러가지 경우에 대해서 상세하게 테스트를 작성해주셨네요 👍👍

2023-01-30 13:13 UTC, malibinYun commented on domain/src/test/java/com/malibin/study/domain/lotto/ticket/LottoTicketTest.kt
> +    }
저는 사실 정상적으로 생성하는 경우는 테스트하지 않아도 무방하다고 생각해요.
굳이 해본다면, exception이 발생하지 않았다 정도로 테스트해도 좋아 보여요.
현재도 틀린 케이스는 아니라고 생각해요 :)

2023-01-30 13:13 UTC, malibinYun commented on domain/src/test/java/com/malibin/study/domain/lotto/ticket/LottoTicketTest.kt
> +        // when
테스트 코드에 로직을 넣는 것은, 읽는 사람에게 한 번 더 머리를 굴리는 일을 하게 만들어요.
그렇게 설명서를 읽는 데 자꾸 멈추게 되면, 가독성에 방해를 줍니다.
그래서 데이터를 준비할 때는 (1..7).map... 처럼 로직을 쓰는 것 보다, 하드코딩으로 재료(given)을 준비해주는 것이 바람직해요 :)

2023-01-30 13:13 UTC, malibinYun commented on domain/src/test/java/com/malibin/study/domain/lotto/ticket/LottoTicketTest.kt
> +        assertThat(exception).isNull()
> Result.getOrNull()로 예외처리를 하였는데 exceptionOrNull() 함수를 사용해서 어떤 예외인지까지 처리하는게 좋으려나요 

네~! 어떤 에러가 났는 지 자세하게 테스트할 수록 코드를 설명하는 데 좋아져요.
기본 제공 Exception 객체 말고도, 다른 Custom Exception이 발생하거나,
한 메서드(혹은 생성자)를 생성할 때 여러 종류의 에러가 발생할 수도 있는데요, 이럴때 구분할 수 있는 것은 어떤 Exception인지, 어떤 message를 출력하고 있는지로 파악할 수 있어요.

단순히 getOrNull을 한다면, 지금은 runCatching 블럭에 생성자가 있어서 해당되지 않지만,
null을 반환하는 메서드를 실행시킨다면, 이게 null을 실제로 반환한 것인지, exception이 발생한 것인지 구분할 수 없어서 테스트 코드를 읽기 어려워져요 :)

그렇기에, 명확하게 Exception에 대한 테스트이니, exceptionOrNull을 호출하는 것이 더 명확한 의미 전달을 할 수 있어요 😊

2023-01-30 13:13 UTC, malibinYun commented on domain/src/test/java/com/malibin/study/domain/lotto/ticket/LottoTicketTest.kt
> +    fun `countMatchingNumbers() 는 LottoTicket의 LottoNumber와 다른 LottoTicket의 LottoNumber를 비교하여 일치하는 숫자의 개수를 반환한다`() {
> 조금 길더라도 테스트 함수 네이밍을 자세하게 하는게 좋으려나요..

아마 이 메서드 명 때문에 고민이셨던 것 같아요.
자세하게 묘사하는 것은 중요하지만, 너무 상세한 기능 나열은 오히려 읽기 힘들어지기도 해요. 

아래 두 네이밍을 비교해볼까요?
1. 가스레인지를켜고냄비에물을500cc붓고끓으면스프와면을넣고3분기다리기
2. 라면끓이기

명확한 의미 전달을 위해서 글쓰기를 한다고 생각하면 좋습니다 😊

2023-01-30 13:13 UTC, malibinYun commented on domain/src/test/java/com/malibin/study/domain/lotto/ticket/LottoTicketTest.kt
> +    fun `has() 는 LottoTicket에 특정 LottoNumber가 포함되어 있는지 확인한다`(num: Int, expected: Boolean) {
Paramenterized Test를 아주 잘 활용해주셨네요! 👍👍

2023-01-31 08:31 UTC, murjune commented on domain/src/test/java/com/malibin/study/domain/lotto/result/MoneyTest.kt
> +
> 다만, 사용하게 되면, when 과 then이 하나로 합쳐지는 상황이 발생해요.  
이 생각을 못했네요!! 답변 감사합니다 ㅎ ㅎ

2023-01-31 08:32 UTC, murjune commented on domain/src/test/java/com/malibin/study/domain/lotto/ticket/LottoTicketTest.kt
> +        assertThat(exception).isNull()
명쾌한 답변 감사합니다 😃

2023-01-31 08:53 UTC, murjune commented on domain/src/test/java/com/malibin/study/domain/lotto/ticket/LottoTicketTest.kt
> +    }
> 저는 사실 정상적으로 생성하는 경우는 테스트하지 않아도 무방하다고 생각해요.  

혹시 이 이유가 테스트 코드 역시 유지보수의 대상이기 때문에 리소스가 발생하기 때문일까요..?  
저는 저번 스터디에서 테스트 코드가 코드의 품질과 신뢰성을 높여주는 것과 더불어 해당 객체의 설명서 역할을 하는 것이라고 이해를 해서요  
남들이 제 테스트 코드를 봤을 때, 이해를 돕기 위해 정상적으로 생성하는 경우도 테스트를 해봤습니다 😄

2023-01-31 08:54 UTC, murjune commented on domain/src/test/java/com/malibin/study/domain/lotto/ticket/LottoTicketTest.kt
> +        // when
> 테스트 코드에 로직을 넣는 것은, 읽는 사람에게 한 번 더 머리를 굴리는 일을 하게 만들어요.  

오.. 전혀 이런 생각을 하지 못했는데 배워갑니다 👍 👍 👍

2023-01-31 12:39 UTC, malibinYun approved these changes
1단계 미션 고생 많으셨어요~
피드백 반영을 잘 해주셨네요!!
테스트 작성이 익숙해지까지 다른 미션들도 응원할게요!

코멘트 남겨두었으니 확인해보시고, 피드백은 다음 미션에 반영해주세요!
다음 미션을 위해 머지하겠습니다~

2023-01-31 12:39 UTC, malibinYun commented on domain/src/test/java/com/malibin/study/domain/lotto/LottoNumberTest.kt
> +        )
assertAll의 활용 아주 좋습니다 👍👍

2023-01-31 12:39 UTC, malibinYun commented on domain/src/test/java/com/malibin/study/domain/lotto/LottoNumberTest.kt
> +        )
assertThat(exception)의 hasMessageThat() 이란 메서드를 활용해 보는 것은 어떨까요?

2023-01-31 12:39 UTC, malibinYun commented on domain/src/test/java/com/malibin/study/domain/lotto/ticket/LottoTicketTest.kt
> +    }
정상 생성에 대한 설명을 나타내는 의도는 아주 좋다고 생각해요!! 👍
다만 검증문은 고민을 해봐야 할 것 같아요 🙂

2023-01-31 12:39 UTC, merged

2023-01-31 15:03 UTC, murjune commented on domain/src/test/java/com/malibin/study/domain/lotto/LottoNumberTest.kt
> +        )
오 그런 메서드가 있는지 몰랐네요!! 반영하겠습니다