2단계 미션 제출합니다.
MalibinStudy/LottoApp pull request #16
Opened 2023-01-31 16:16 UTC by ChunBaee

Prize에서 당첨갯수가 0인데 보너스 포함 여부가 true 일 때 (구조적 오류) 는 역시 기능 자체에 구현되지 않은 부분이므로 테스트에서 제외하는게 좋을까요?

만약 하드코딩한 값이 통과되었으나, 실제로 실행 시 임의의 값에서 오류가 발생하여 테스트 케이스를 고쳐야 하는 경우도 생길 수 있나요?
만약 그렇다면 단순히 테스트 횟수를 늘리기보다는 계속해서 테스트 코드를 리팩토링 하는 방법이 좋은가요?

2023-02-01 15:42 UTC, malibinYun requested changes
2단계 미션 고생 많으셨어요!
테스트 코드 작성에 점점 익숙해지셨으면 좋겠네요 :)

코멘트 달아두었으니 확인 부탁드려요!
리뷰 반영하시고, 다시 리뷰 요청 부탁드립니다~ 🙂


> Prize에서 당첨갯수가 0인데 보너스 포함 여부가 true 일 때 (구조적 오류) 는 역시 기능 자체에 구현되지 않은 부분이므로 테스트에서 제외하는게 좋을까요?

이 부분은 코멘트에 남겨두었어요!

> 만약 하드코딩한 값이 통과되었으나, 실제로 실행 시 임의의 값에서 오류가 발생하여 테스트 케이스를 고쳐야 하는 경우도 생길 수 있나요?
만약 그렇다면 단순히 테스트 횟수를 늘리기보다는 계속해서 테스트 코드를 리팩토링 하는 방법이 좋은가요?

네~ 테스트 횟수를 늘려도 중간에 통과되지 못하는 테스트는 반드시 생길거예요.
정확하게 어떤 케이스인지 잘 생각이 나지 않지만, 프로덕션 코드가 계속 바뀌듯이, 테스트코드도 계속해서 리팩터링해야할 수 있어요!

2023-02-01 15:42 UTC, malibinYun commented on domain/src/test/java/com/malibin/study/domain/lotto/result/PrizeTest.kt
> +    }
내부 금액을 가지고 비교하기 보다, 실제 Prize 객체로 비교해보는 것은 어떨까요?

2023-02-01 15:42 UTC, malibinYun commented on domain/src/test/java/com/malibin/study/domain/lotto/result/PrizeTest.kt
> +    }
나머지 모든 당첨 결과에도 테스트 케이스를 만들어보세요 :)

2023-02-01 15:42 UTC, malibinYun commented on domain/src/test/java/com/malibin/study/domain/lotto/result/PrizeTest.kt
> +    }
미당첨 결과도 결국 결과이기 떄문에, 위 테스트 케이스로 합쳐질 수 있겠네요 :)

2023-02-01 15:42 UTC, malibinYun commented on domain/src/test/java/com/malibin/study/domain/lotto/result/PrizeTest.kt
> +
보너스볼이 있어야 2등인 것만 위 ParameterizedTest를 통해 나타내도 충분하다고 생각해요.
더 디테일하게 테스트한다면, 어떤 등수들은 보너스볼에 상관 없다는 테스트를 만들어도 좋겠네요 🙂

2023-02-01 15:42 UTC, malibinYun commented on domain/src/test/java/com/malibin/study/domain/lotto/ticket/WinningTicketTest.kt
> +        assertThat(assertException).hasMessageThat().contains("보너스 번호 ($b)는 당첨번호(${a.joinToString(", ")})와 중복될 수 없습니다.")
한 라인이 너무 길어져서 가독성이 떨어집니다.
또, a, b 처럼 의미 없는 변수를 사용하면 더욱 테스트 가독성을 떨어뜨리게 돼요.

given, when, then 패턴으로 나누어서 테스트를 작성해보세요 :)

2023-02-01 15:42 UTC, malibinYun commented on domain/src/test/java/com/malibin/study/domain/lotto/ticket/WinningTicketTest.kt
> +            LottoTicket(*otherTicket))
이 부분도 라인이 너무 길어서 쪼개어볼 수 있겠어요.
정말로 테스트하고 싶은 부분 만을 잘 쪼개어서 라인 분리 하는 연습을 해볼까요? 😊

2023-02-01 15:42 UTC, malibinYun commented on domain/src/test/java/com/malibin/study/domain/lotto/ticket/WinningTicketTest.kt
> +        assertThat(assertValue).isEqualTo(Prize.First)
테스트 코드에서는 콘솔 출력을 할 필요가 없답니다 :)

2023-02-01 15:42 UTC, malibinYun commented on domain/src/test/java/com/malibin/study/domain/lotto/ticket/WinningTicketTest.kt
> +        assertThat(assertValue.toString()).isEqualTo("{Fifth=1, First=1}")
toString으로 비교하기보다는, 실제 map객체를 만들어보세요 :)
```kotlin
mapOf<Prize, Int>(~~)
```

2023-02-03 13:59 UTC, malibinYun approved these changes
2단계 미션 고생 많으셨어요!!
테스트 작성은 좀 익숙해지셨을까요 ?_?

코멘트 남겨 두었으니 확인 부탁드릴게요!
피드백은 다음 미션 진행 하시면서 반영해주세요 :)

2023-02-03 13:59 UTC, malibinYun commented on domain/src/test/java/com/malibin/study/domain/lotto/result/PrizeTest.kt
> +
테스트를 하게 되더라도, name을 꺼내 비교하기 보다, 찾은 Prize 자체를 직접 비교해보는 것은 어떨까요?

2023-02-03 13:59 UTC, malibinYun commented on domain/src/test/java/com/malibin/study/domain/lotto/ticket/WinningTicketTest.kt
> +    }
joinToSTring도 결국 로직이기에, 테스트가 거짓말을 할 가능성이 있어요.
검증부는 하드코딩해보는 것은 어떨까요?

2023-02-03 13:59 UTC, malibinYun commented on domain/src/test/java/com/malibin/study/domain/lotto/ticket/WinningTicketTest.kt
> +        val otherTicket = LottoTicket(*intArrayOf(1, 2, 3, 4, 5, 6))
`varargs numbers:Int` 이 파라미터는 꼭 intArray를 만들어서 넣지 않고,
LottoTicket(1, 2, 3, 4, 5, 6) 이렇게 넣을 수 있어요 :)

2023-02-03 13:59 UTC, malibinYun commented on domain/src/test/java/com/malibin/study/domain/lotto/ticket/WinningTicketTest.kt
> +        )
`Pair(Prize.Fifth, 1)`는 `Prize.First to 1`
이렇게도 작성할 수 있답니다 :)

2023-02-03 13:59 UTC, malibinYun commented on domain/src/test/java/com/malibin/study/domain/lotto/ticket/WinningTicketTest.kt
> +    }
assert구문은 toString으로 비교하지 않고, 직접 값을 비교해보는 것은 어떨까요?

2023-02-03 13:59 UTC, merged

2023-02-04 08:25 UTC, ChunBaee commented on domain/src/test/java/com/malibin/study/domain/lotto/ticket/WinningTicketTest.kt
> +    }
코틀린 내장함수인데도 그럴 가능성이 있나요??

2023-02-05 12:43 UTC, malibinYun commented on domain/src/test/java/com/malibin/study/domain/lotto/ticket/WinningTicketTest.kt
> +    }
함수 자체는 내장 함수여서 그럴 일이 없을 수 있어요.
다만, 모든 실수의 원천은 휴먼에러에서 시작돼요.
lottoNumbers 내에 joinToString(param1: String) 같은 메서드를 실수로 혹은, 고의로 만들었다면, 코틀린 내장함수와는 별개로 다른 기능을 할 수도 있게 돼요.
그렇기에 테스트에서는 최대한 하드코딩으로 비교군을 준비해주는 것이 바람직해요 :)