Step3 미션 제출합니다
MalibinStudy/LottoApp pull request #17
Opened 2023-02-01 08:32 UTC by stopkite

<img width="876" alt="image" src="https://user-images.githubusercontent.com/62979643/215990345-6bb5fac5-3865-4304-9e6f-52b3ee8feb38.png">
수동 티켓 생성시 아무리 생각해도 클래스 변수를 받아오는 게 흐름이 안 맞는 거 같아서
클래스 변수를 생략하고 함수를 호출했는데 동작이 되더라구요! 

`val expectedLottoTicket = LottoTicketGenerator().createManualTicket(setOf(1, 2, 3, 4, 5, 6))`

그런데 generatingLottoNumbersStrategy가 클래스 매개변수?인 거 같은데 어떻게 생략이 가능했던 건지 이유가 궁금합니다!

2023-02-02 12:30 UTC, malibinYun requested changes
3단계 미션 고생 많으셨어요!!

랜덤에 대한 테스트를 혹시 해보셨나요 ?_?
가장 어려울 수 있는 영역이었는데, 한 방에 해치우셔서 크게 리뷰 드릴 점이 없었네요 ㅎ_ㅎ...

코멘트 남겨두었으니, 리뷰 반영하시고 다시 리뷰 요청 부탁드릴게요!!

> 그런데 generatingLottoNumbersStrategy가 클래스 매개변수?인 거 같은데 어떻게 생략이 가능했던 건지 이유가 궁금합니다!

네~ LottoTicketGenerator에는 GeneratingLottoNumbersStrategy 구현체를 생성자로부터 받게 되어있어요.
여기서 바로 `LottoTicketGenerator()` 이런 형태로 생성할 수 있는 이유는, 생성자에 Default Parameter를 지정해주어서예요.
아래 코드를 보시면 이해가 빠릅니다 🙂
```kotlin
class LottoTicketGenerator(
    private val generatingLottoNumbersStrategy: GeneratingLottoNumbersStrategy = RandomLottoNumbersStrategy(), // 이곳에 아무것도 들어 오지 않으면 RandomLottoNumbersStrategy() 이 객체를 넣는다는 의미예요 :)
) 
```

> 그리고 자동 티켓 생성에는 왜 특별히 sortedBy()를 쓰셨는지가 궁금합니다!

보여줄 때 숫자가 중구난방으로 되어있으면 보기 불편해서 정렬했어요! 😊

2023-02-02 12:30 UTC, malibinYun commented on domain/src/test/java/com/malibin/study/domain/lotto/generator/LottoTicketGeneratorTest.kt
> +        ).createAutoTicket()
오..!! 
랜덤 테스트를 정말 잘 구현해주셨네요!! 👍👍

2023-02-02 12:30 UTC, malibinYun commented on domain/src/test/java/com/malibin/study/domain/lotto/generator/LottoTicketGeneratorTest.kt
> +    }
`Truth.` 는 static import를 하면 지워볼 수 있어요.
assertThat() 까지 쳐야 alt-enter (option-enter) 커맨드를 사용할 수 있는 게 흠이지만, 코드를 조금이나마 줄여볼 수 있답니다 :)

2023-02-02 12:30 UTC, malibinYun commented on domain/src/test/java/com/malibin/study/domain/lotto/generator/LottoTicketGeneratorTest.kt
> +        val actualLottoTicket = LottoTicket(1, 2, 3, 4, 5, 6)
setOf(1,2,3,4,5,6)과 
val actualLottoTicket = LottoTicket(1, 2, 3, 4, 5, 6)
LottoTicketGenerator()
까지가 테스트를 위한 준비 재료라고 볼 수 있겠네요 :)

테스트를 하는 것은 createManualTicket()이니, 이 부분을 when절로 옮기면 좋겠어요! 🙂

2023-02-02 12:30 UTC, malibinYun commented on domain/src/test/java/com/malibin/study/domain/lotto/ticket/WinningTicketTest.kt
> +            Prize.Lose to 3
이 부분도 테스트를 위한 재료 준비 단계로 볼 수 있어요 :)

2023-02-03 16:41 UTC, stopkite commented on domain/src/test/java/com/malibin/study/domain/lotto/generator/LottoTicketGeneratorTest.kt
> +        ).createAutoTicket()
흐흐 감사합니다 :) (왕뿌듯!)

2023-02-03 17:23 UTC, stopkite commented on domain/src/test/java/com/malibin/study/domain/lotto/generator/LottoTicketGeneratorTest.kt
> +        val actualLottoTicket = LottoTicket(1, 2, 3, 4, 5, 6)
작성해주신 피드벡을 보고 자동 티켓 생성 테스트의 경우에도 배치를 바꿔보았는데 맞게 한 걸까요? :)

2023-02-03 17:24 UTC, stopkite commented on domain/src/test/java/com/malibin/study/domain/lotto/ticket/WinningTicketTest.kt
> +            Prize.Lose to 3
넵 :) 수정완료 했습니다!

2023-02-05 12:18 UTC, malibinYun approved these changes
1주차 미션 고생 많으셨어요!! 🎉
미션 잘 진행해주셔서 이번엔 크게 피드백 드릴 게 없었네요 :)
다음 2주, 3주차 미션도 꼭 진행해보시길 바라요!!
다른 미션들도 화이팅입니다 :) 💪🔥

2023-02-05 12:18 UTC, malibinYun commented on domain/src/test/java/com/malibin/study/domain/lotto/generator/LottoTicketGeneratorTest.kt
> +            )
이 부분의 로또숫자생성전략 또한 테스트를 위한 준비 단계라고 볼 수 있어요 :)
검증하려는 로직은 `createAutoTicket()` 이 메서드 뿐입니다 🙂

2023-02-05 12:18 UTC, merged