Step1 미션 제출합니다
MalibinStudy/LottoApp pull request #8
Opened 2023-01-28 04:52 UTC by stopkite

[Money] 
+ amount에 null과 공백이 들어가는지도 체크 하려다 그건 컴파일 에러로 잡힐 것 같아서 생략했는데 type체크까지 테케에서 해야될까요?
+ 마찬가지로 +,- 연산자 외에 '곱하기'나 '나머지 '*','%' 연산자가 들어오면 안된다는 것도 테스트 케이스로 작성하고 싶었는데 애초에 override된 연산자가 없어서 작성을 못했습니다. 이런건 테스트 할 필요가 없는게 맞나요?

[LottoTicketTest]
+ 여러 가지 경우의 예시를 확인하고 싶어서 @ParameterizedTest과 @MethodSource를 사용했는데 
_테스트의 횟수는 중요하지 않다_는 슬랙 답변을 보고 다시 생각해보니 여기도 그냥 여러 배열을 받을 필요없이 @Test로 하는게 더 좋았을 거 같네요ㅎㅎㅎㅎ

2023-01-28 07:48 UTC, malibinYun requested changes
테스트를 잘 작성해주셨네요!!
처음 테스트를 접해보신 거라면, 평소와 완전히 다른 스타일로 코드를 써보는 거라 엄청 어색했을 것 같아요 :)
미션을 계속 해보시면서 테스트 코드 작성에 익숙해지셨으면 좋겠네요! 

코멘트 달아두었으니, 확인해보시고 리뷰 반영이 끝나면 슬랙에 저를 멘션해서 리뷰 반영했다고 메시지 남겨주세요! 혹은, 이 PR에 코멘트를 달아주셔도 됩니다.

> amount에 null과 공백이 들어가는지도 체크 하려다 그건 컴파일 에러로 잡힐 것 같아서 생략했는데 type체크까지 테케에서 해야될까요?

아니요! 컴파일러가 잡아주는 것 까지 할 필요는 없어요. 

> 마찬가지로 +,- 연산자 외에 '곱하기'나 '나머지 '*','%' 연산자가 들어오면 안된다는 것도 테스트 케이스로 작성하고 싶었는데 애초에 override된 연산자가 없어서 작성을 못했습니다. 이런건 테스트 할 필요가 없는게 맞나요?

네~! Money에 대해 선언해준 연산자는 단 2개 이기 때문에 만들어 둔 기능이 의도에 맞게 동작하는 지 테스트를 해주면 돼요. 없는 기능에 대해서 테스트를 할 필요는 없답니다 😊

> 여러 가지 경우의 예시를 확인하고 싶어서 @ParameterizedTest과 @MethodSource를 사용했는데
_테스트의 횟수는 중요하지 않다_는 슬랙 답변을 보고 다시 생각해보니 여기도 그냥 여러 배열을 받을 필요없이 @test로 하는게 더 좋았을 거 같네요ㅎㅎㅎㅎ

이 부분은 리뷰에 남겨두었어요!

2023-01-28 07:48 UTC, malibinYun commented on README.md
> ++ 로또에 일치하는 번호의 개수를 알 수 있다
기능 명세를 잘 작성해주셨네요! 👍👍

2023-01-28 07:48 UTC, malibinYun commented on domain/src/test/java/com/malibin/study/domain/lotto/LottoNumberTest.kt
> +    }
지금 테스트는 LottoNumber와는 연관성이 없이, Integer가 범위 내에 있는지에 대한 테스트예요.
LottoNumber.of로 생성된 객체로 테스트하는 것이 의도에 맞아 보여요!

1~45를 전부 테스트해보는 것도 좋은 방법일 수 있지만, 저는 아래 만들지 못하는 것들만 테스트해도 충분하다고 생각해요!

2023-01-28 07:48 UTC, malibinYun commented on domain/src/test/java/com/malibin/study/domain/lotto/LottoNumberTest.kt
> +    }
유효하지 않은 숫자에 대한 테스트를 잘 작성해주셨네요! 👍👍
그리고 여러 검증문에 대한 assertAll을 활용해주셨네요 👍👍

2023-01-28 07:48 UTC, malibinYun commented on domain/src/test/java/com/malibin/study/domain/lotto/result/MoneyTest.kt
> +    }
음수가 들어오면 안되는 게 중요하니, 1개의 음수에 대해서만 테스트해도 충분하다고 생각해요 :)

2023-01-28 07:48 UTC, malibinYun commented on domain/src/test/java/com/malibin/study/domain/lotto/result/MoneyTest.kt
> +    }
이미 위에서 + 연산에 대해 정상 작동함을 검증 했기 때문에 +연산이 이상하게 동작할 것이라는 테스트 케이스는 없어도 충분해요! 🙂

추가로 덧붙이면,
Money(5_000)이 exception이 발생하지 않는 것은 자명해요.
그렇기 때문에 Exception이 발생하지 않을 곳에 runCatching을 쓴다면,
Money(5_000) 에는 Exception이 발생하는 것으로 오해를 만들 수 있어요.

2023-01-28 07:48 UTC, malibinYun commented on domain/src/test/java/com/malibin/study/domain/lotto/result/MoneyTest.kt
> +    }
이 부분도 - 연산에 대해 검증 했으므로 충분해요.
다만, 뺐을 때 음수가 되는 경우를 테스트 해볼 수도 있겠네요 😊

2023-01-28 07:48 UTC, malibinYun commented on domain/src/test/java/com/malibin/study/domain/lotto/cal/AverageCalculatorTest.kt
> +        fun providesLottoTickets(): List<Arguments> =
MethodSource를 활용하려면 반드시 `@JvmStatic`을 붙여야해요.
이 테스트 파일은 테스트가 크래시가 나고 있네요!

2023-01-28 07:48 UTC, malibinYun commented on domain/src/test/java/com/malibin/study/domain/lotto/ticket/LottoTicketTest.kt
> +    }
테스트 내부에는 if 문 같은 로직을 활용하지 않는 것이 바람직해요.
actualException에 어떤 값이 할당 되는 지에 대해 상관 없이, assert문을 실행시키면 돼요.
이 테스트에서 중요한 것은 `주어진 intArray를 set으로 바꿨을 때의 크기와 intArray의 사이즈가 다르다` 가 아니라, `중복 번호가 주어진 로또 번호` 가 중요하기 때문이에요. 

주어진 번호로 티켓을 만들었을 때 exception이 발생하는 것에 초점을 맞추면 됩니다. 😊

테스트 코드에서 assert 구문을 실행시키지 않고 종료되면 그것 또한 테스트는 통과로 인식해요. 실제로 if 블럭을 지우시고 동작 시키면 테스트가 통과되는 것을 볼 수 있을 거예요.

2023-01-28 07:48 UTC, malibinYun commented on domain/src/test/java/com/malibin/study/domain/lotto/ticket/LottoTicketTest.kt
> +    }
이 두 테스트 케이스는 위의 중복 테스트와 함께 묶어서
`유효하지 않은 숫자들로 LottoTicket을 생성할 수 없다` 라는 Parameterized Test를 해볼 수 있겠네요 🙂

2023-01-28 07:48 UTC, malibinYun commented on domain/src/test/java/com/malibin/study/domain/lotto/ticket/LottoTicketTest.kt
> +    }
네~! 이 부분은 질문 주신 부분처럼 반복에는 큰 의미를 부여하기는 어려워요.
오히려, (1,true)와 (7, false) 쌍을 파라미터로 받아서 티켓에 번호가 들어있는 지 체크하는 테스트를 써보는 것도 좋겠네요!

2023-01-28 07:48 UTC, malibinYun commented on domain/src/test/java/com/malibin/study/domain/lotto/ticket/LottoTicketTest.kt
> +        assertThat(lottoTicket.countMatchingNumbers(otherLottoTicket)).isEqualTo(matchNumber)
이 테스트는 케이스가 최대 7개이니, 7개를 모두 파라미터에 추가해보는 것은 어떨까요?

2023-01-28 16:48 UTC, stopkite commented on README.md
> ++ 로또에 일치하는 번호의 개수를 알 수 있다
감사합니다~ : )

2023-01-28 16:50 UTC, stopkite commented on domain/src/test/java/com/malibin/study/domain/lotto/LottoNumberTest.kt
> +    }
오 그렇네요. 다시 보니까 LottoNumber랑은 전혀 상관없는 코드군요! 
만들지 못하는 코드가 있어서 해당 테스트 케이스는 삭제했습니다!

2023-01-28 16:52 UTC, stopkite commented on domain/src/test/java/com/malibin/study/domain/lotto/result/MoneyTest.kt
> +    }
<img width="716" alt="image" src="https://user-images.githubusercontent.com/62979643/215278757-ee59d8de-6ae5-4c47-b42b-dca67689e4a9.png">

 @ParameterizedTest를 @Test로 변경하였습니다.

2023-01-28 16:53 UTC, stopkite commented on domain/src/test/java/com/malibin/study/domain/lotto/ticket/LottoTicketTest.kt
> +    }
if 블럭 삭제했습니다! 덕분에 이해가 잘 되었습니다 : ) !

2023-01-28 16:58 UTC, stopkite commented on domain/src/test/java/com/malibin/study/domain/lotto/ticket/LottoTicketTest.kt
> +    }
@malibinYun 
<img width="699" alt="image" src="https://user-images.githubusercontent.com/62979643/215278911-220fc400-4fdc-4f8a-9a1f-ff6d9d8f1f76.png">

<img width="427" alt="image" src="https://user-images.githubusercontent.com/62979643/215279010-22ca0afa-0949-4aa9-b291-550011eaaac9.png">

중복인 경우, 로또 번호의 개수가 6보다 크거나 작은 경우를 묶어서 한꺼번에 처리했는데
그런데 이렇게 되면 **중복이 문제**인지 **초과가 문제**인지 명확히 구분할 수 없지 않나요?!

2023-01-28 17:01 UTC, stopkite commented on domain/src/test/java/com/malibin/study/domain/lotto/ticket/LottoTicketTest.kt
> +        assertThat(lottoTicket.countMatchingNumbers(otherLottoTicket)).isEqualTo(matchNumber)
일치하는 번호의 개수가 0~6개라서 7개라고 말씀하신 게 맞나요? 수정해서 반영하였습니다 : )!

2023-01-29 03:26 UTC, malibinYun approved these changes
1단계 미션 고생 많으셨어요~!
테스트를 작성하는 게 조금은 익숙해지셨을까요 ?_?
미션 완주하면서 완전히 익숙해지셨으면 좋겠네요 😊

코멘트 남겨두었으니 확인해보시고, 피드백은 다음 미션에 반영해주세요!
다음 미션을 위해 머지하겠습니다~

2023-01-29 03:26 UTC, malibinYun commented on domain/src/test/java/com/malibin/study/domain/lotto/result/MoneyTest.kt
> +        val actualException = runCatching { Money(actualAmount).amount }.exceptionOrNull()
given과 when의 순서가 잘못 표기되어있네요! 주석의 순서를 바꿔주시면 됩니다 :)

2023-01-29 03:26 UTC, malibinYun commented on domain/src/test/java/com/malibin/study/domain/lotto/result/MoneyTest.kt
> +        val actualException = runCatching { Money(actualAmount).amount }.exceptionOrNull()
runCatching 블럭 내에서 amount를 꺼내지 않아도 충분합니다 🙂

2023-01-29 03:26 UTC, malibinYun commented on domain/src/test/java/com/malibin/study/domain/lotto/ticket/LottoTicketTest.kt
> +    fun `로또 티켓과 일치 하는 번호의 존재 여부를 확인할 수 있다`(number: Int, isSame: Boolean) {
이 테스트는 MethodSource 대신 Csv Source를 활용해보는 것은 어떨까요?

2023-01-29 03:26 UTC, malibinYun commented on domain/src/test/java/com/malibin/study/domain/lotto/ticket/LottoTicketTest.kt
> +    }
비교 로직을 넣는 것 보다 직접 비교하는 것이 더 바람직해 보입니다 :)
```suggestion
        // then
        assertThat(lottoTicket.has(lottoNumber)).isEqualTo(isSame)
    }
```

2023-01-29 03:26 UTC, malibinYun commented on domain/src/test/java/com/malibin/study/domain/lotto/ticket/LottoTicketTest.kt
> +        assertThat(lottoTicket.countMatchingNumbers(otherLottoTicket)).isEqualTo(matchNumber)
when then을 합쳐서 작성할 경우 코드가 길어져서 한 번에 읽기 불편해질 수 있어요.
`lottoTicket.countMatchingNumbers(otherLottoTicket)`
이 부분은 따로 변수에 할당해보면 이름에 의미도 부여하고, 더 짧게 써볼 수 있겠네요 :)

2023-01-29 03:27 UTC, merged

2023-01-29 03:30 UTC, malibinYun commented on domain/src/test/java/com/malibin/study/domain/lotto/ticket/LottoTicketTest.kt
> +    }
네! 맞아요. 말씀하신대로 명확히 구분할 수 없어요.
이런 명세와 요구사항을 정확하게 전달하고 싶으면 분리해서 각 테스트 코드를 작성해주시면 됩니다 :)

다만, 제가 한꺼번에 해도 좋겠다는 제안을 드렸던 것은 현재 로또 티켓 코드 내에 해당 요구사항이 정확하게 분리되어서 Exception 메시지를 던지지 않고 있기 때문이었어요.

제가 드린 제안이 맞을 수도, 틀릴 수도 있고, 취향의 영역일 수도 있어요. 잘 생각해보시고 다르게 작성해보셔도 괜찮아요! 😊

2023-01-29 03:30 UTC, malibinYun commented on domain/src/test/java/com/malibin/study/domain/lotto/ticket/LottoTicketTest.kt
> +        assertThat(lottoTicket.countMatchingNumbers(otherLottoTicket)).isEqualTo(matchNumber)
네~ 맞아요! 잘 잘성해주셨습니다 🙂