1주차] 1, 2단계 미션입니다.
MalibinStudy/LottoApp pull request #9
Opened 2023-01-28 08:52 UTC by ChunBaee

Input 으로 List를 주고싶을 때, methodSource를 제외한 방법은 없을까요?

올바른 테스트는 정상적으로 동작하는 것 / 동작하지 않는 것 모두를 테스트해보는게 맞을까요?

타겟 클래스의 모든 메서드들을 전부 테스트해보는것이 좋나요?

2023-01-28 09:14 UTC, malibinYun commented
안녕하세요 :)
슬랙 DM 남겨두었으니 확인 후 PR 업데이트 부탁드릴게요! 🙂

2023-01-29 07:18 UTC, malibinYun requested changes
테스트를 열심히 작성해주셨네요 :)
평소에는 작성해본 적 없는 코드를 작성해보느라 어색했을 것 같아요 :)
미션을 하시면서 익숙해지셨으면 좋겠네요! 😊

테스트가 통과되지 않는 케이스가 꽤 있었어요.
다음에는 꼭 모든 테스트가 통과하는 상태로 미션을 제출해주세요!
![image](https://user-images.githubusercontent.com/44341119/215310643-50881a9a-e7cf-4295-9e0f-73eaad38c34b.png)

또, 테스트 명을 쓸 때 백틱(`)으로 감싸져있다면, 스페이스를 그대로 사용해도 돼요. 언더바를 사용할 필요가 없습니다.
백틱으로 감싸지 않았을 때만 언더바를 활용해주시면 돼요!

전반적으로 테스트 명이 구체적이지 않고 추상적인 의미로 적혀있었어요. 처음 보는 사람도 이해할 수 있게끔 구체적으로 테스트명을 작성해보는 연습을 해보시길 바라요 😊

> Input 으로 List를 주고싶을 때, methodSource를 제외한 방법은 없을까요?

네. 원시 타입을 제외한 입력 값들을 지원하기 위해 나온 것이 MethodSource랍니다 :)

> 올바른 테스트는 정상적으로 동작하는 것 / 동작하지 않는 것 모두를 테스트해보는게 맞을까요?

이 부분은 코멘트로 달아두었으니 확인해주세요! 🙂

> 타겟 클래스의 모든 메서드들을 전부 테스트해보는것이 좋나요?

네, 객체가 원하는 의도대로 동작하는 지 검증하기 위해서는 public method들을 모두 테스트해봐야겠지요. 다만, private method는 public method를 테스트함으로써 간접적으로 테스트해본다고 생각하면 좋습니다 :)

리뷰 반영 후에 메시지 남겨주세요! 슬랙에 저를 멘션하거나, 이 PR에 코멘트를 달아주셔도 됩니다 :)

2023-01-29 07:18 UTC, malibinYun commented on domain/src/test/java/LottoNumberTest.kt
> +        val actualNumber = LottoNumber.of(number)
테스트 명에 LottoNumber가 정상인 것은 어떤 상황인지, 잘 동작하는 것은 어떻게 잘 동작하는 것 인지가 모두 빠져있어요.
테스트 명은 구체적으로 작성하는 것이 좋아요 :)
아무 것도 모르는 사람이 테스트 코드를 봤을 때 프로덕션 코드의 설명서의 역할을 해줄 수 있어야해요. 🙂
`로또 번호 숫자 범위의 숫자로 LottoNumber를 생성할 수 있다` 정도가 구체적인 이름이 될 수 있겠네요 :)

다만, 1~45를 전부 테스트해보는 것도 좋은 방법일 수 있지만, 저는 아래 만들지 못하는 것들만 테스트해도 충분하다고 생각해요!

2023-01-29 07:18 UTC, malibinYun commented on domain/src/test/java/LottoNumberTest.kt
> +    @ParameterizedTest
이 테스트는 범위를 벗어난 숫자 하나씩만 테스트해도 충분하다고 생각해요 :)
동일한 경우의 무의미한 반복은 지양해야합니다.

2023-01-29 07:18 UTC, malibinYun commented on domain/src/test/java/LottoNumberTest.kt
> +    }
이건 어떤 것을 테스트하고 싶은지 의도를 알기 어렵네요. 코멘트로 설명을 조금 적어주실 수 있을까요 ?_? 같이 이야기해봐요.

2023-01-29 07:18 UTC, malibinYun commented on domain/src/test/java/com/malibin/study/domain/lotto/result/MoneyTest.kt
> +    }
적어도 몇 이하, 메시지에 문자열 조각이 포함되어있는지,
이러한 것은 테스트가 거짓말을 할 경우가 생겨요.
리팩터링 실패로 input이 3이 들어갔지만, 내부적으로 -10 배를 해서 exception에 -30이 인풋이었다는 메시지가 나타난다면,
실제로 3이 들어가있기 때문에 테스트는 통과됩니다.

테스트에는 범위를 주어서 검증하는 것 보다, 정확하게 어떤 값을 기대하는 지 검증하는 것이 좋습니다 :)

연관된 좋은 글을 공유드릴게요 🙂
https://jojoldu.tistory.com/615

2023-01-29 07:18 UTC, malibinYun commented on domain/src/test/java/com/malibin/study/domain/lotto/result/MoneyTest.kt
> +    }
만들 수 없게끔 만들어 놓은 부분에 대해서 테스트를 할 필요는 없어요.

이미 Money 객체는 Long 타입 만을 허용합니다.
만약 이러한 테스트를 해야한다면, 모든 경우의 수를 동원해서 전부 테스트해보아야겠지요.
극단적으로, AndroidContext, Activity, TextView등을 Money의 input으로 넣을 수 없다는 테스트도 만들어야 합니다.

그렇기 때문에, 생성되지 않음을 테스트하고 싶다면, 객체가 생성되지 않는 의도를 담은 부분을 테스트해보면 됩니다.
예를들어, Long을 넣을 수는 있지만, 로직에서는 음수를 넣을 수 없게 되어있어요.
음수를 넣었을 때 Money객체를 만들 수 없음을 테스트 하는 것은,
 의도를 전달하는 설명서의 역할을 할 수 있기 때문에 적절한 테스트 케이스예요 🙂

2023-01-29 07:18 UTC, malibinYun commented on README.md
> +
기능 목록을 잘 작성해주셨네요! 👍👍

2023-01-29 07:18 UTC, malibinYun commented on domain/src/test/java/com/malibin/study/domain/lotto/ticket/LottoTicketTest.kt
> +    }
CsvSource를 적절하게 작성해주셨네요!  👍👍

다만, false, true 인 경우 한 개씩 테스트해도 충분해 보입니다 :)

2023-01-30 05:55 UTC, ChunBaee commented on domain/src/test/java/LottoNumberTest.kt
> +    }
중복된 숫자가 있을 때 여부를 판단하고 싶었는데, Step2 과제를 진행하다보니 파일 중에 있더라구요! 이 부분은 피드백 반영시 제외하도록 하겠습니다!

2023-01-30 12:37 UTC, malibinYun approved these changes
1단계 미션 고생 많으셨어요!
테스트 코드 작성하는 게 이번 미션으로 익숙해지셨으면 좋겠네요 :)

코멘트 남겨두었으니 확인 부탁드려요!
피드백은 다음 미션에 반영해주시면 됩니다. 🙂

2023-01-30 12:37 UTC, malibinYun commented on domain/src/test/java/LottoNumberTest.kt
> +        val number = -1
범위 양 끝의 숫자로 테스트해보면 더욱 의도를 나타내기 좋겠네요 :)

2023-01-30 12:37 UTC, malibinYun commented on domain/src/test/java/com/malibin/study/domain/lotto/result/MoneyTest.kt
> +
같은 경우의 테스트는 한 번으로도 충분해요 :)
각 테스트의 마지막 케이스는 테스트가 실패하는 케이스네요. 테스트는 반드시 성공하게 만드는 것이 좋습니다 :)

2023-01-30 12:37 UTC, merged